export const COORDS: Record<string, { x: number, y: number }> = {
    "Warrington": { x: 100, y: 50 },
    "Leek": { x: 250, y: 50 },
    "Belper": { x: 750, y: 50 },
    "Stoke-on-Trent": { x: 150, y: 110 },
    "Stone": { x: 200, y: 200 },
    "Stafford": { x: 180, y: 300 },
    "Uttoxeter": { x: 450, y: 160 },
    "Derby": { x: 750, y: 150 },
    "Nottingham": { x: 920, y: 120 },
    "Burton-upon-Trent": { x: 650, y: 280 },
    "Cannock": { x: 350, y: 350 },
    "Tamworth": { x: 750, y: 420 },
    "Wolverhampton": { x: 180, y: 420 },
    "Walsall": { x: 450, y: 400 },
    "Coalbrookdale": { x: 100, y: 520 },
    "Dudley": { x: 320, y: 550 },
    "Birmingham": { x: 500, y: 600 },
    "Nuneaton": { x: 820, y: 600 },
    "Coventry": { x: 920, y: 680 },
    "Redditch": { x: 650, y: 720 },
    "Kidderminster": { x: 150, y: 700 },
    "Worcester": { x: 250, y: 780 },
    "Gloucester": { x: 400, y: 820 },
    "Oxford": { x: 850, y: 820 },
    "Shrewsbury": { x: 50, y: 350 },
    "Farm Brewery North": { x: 150, y: 360 },
    "Farm Brewery South": { x: 120, y: 800 }
};

export const EDGES: [string, string][] = [
    ["Cannock", "Farm Brewery North"], ["Birmingham", "Oxford"], ["Warrington", "Stoke-on-Trent"],
    ["Leek", "Stoke-on-Trent"], ["Leek", "Belper"], ["Belper", "Derby"], ["Derby", "Nottingham"],
    ["Burton-upon-Trent", "Cannock"], ["Derby", "Burton-upon-Trent"], ["Stone", "Burton-upon-Trent"],
    ["Stone", "Uttoxeter"], ["Uttoxeter", "Derby"], ["Stoke-on-Trent", "Stone"], ["Stone", "Stafford"],
    ["Stafford", "Cannock"], ["Cannock", "Wolverhampton"], ["Cannock", "Walsall"],
    ["Walsall", "Burton-upon-Trent"], ["Burton-upon-Trent", "Tamworth"], ["Tamworth", "Walsall"],
    ["Tamworth", "Nuneaton"], ["Nuneaton", "Coventry"], ["Walsall", "Birmingham"],
    ["Wolverhampton", "Walsall"], ["Wolverhampton", "Dudley"], ["Coalbrookdale", "Wolverhampton"],
    ["Shrewsbury", "Coalbrookdale"], ["Coalbrookdale", "Kidderminster"], ["Dudley", "Birmingham"],
    ["Dudley", "Kidderminster"], ["Kidderminster", "Worcester"], ["Worcester", "Gloucester"],
    ["Worcester", "Birmingham"], ["Birmingham", "Tamworth"], ["Birmingham", "Coventry"],
    ["Birmingham", "Redditch"], ["Birmingham", "Nuneaton"], ["Redditch", "Oxford"], ["Redditch", "Gloucester"]
];
